# Generated by Django 5.1.5 on 2025-03-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='anamnesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('age', models.IntegerField()),
                ('vaccination', models.BooleanField()),
                ('observation', models.TextField()),
            ],
        ),
    ]
