# Generated by Django 5.1.5 on 2025-02-05 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia_process', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='anamnesis',
            field=models.TextField(max_length=100),
        ),
    ]
