# Generated by Django 5.1.5 on 2025-03-22 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia_process', '0002_alter_review_anamnesis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='anamnesis',
            field=models.TextField(max_length=1000),
        ),
    ]
